name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install node_modules
      working-directory: ./example
      run: npm i
      shell: bash

    - name: Build package
      working-directory: ./example
      run: npm run build
      shell: bash

    - run: git config user.name github-actions
      working-directory: ./example
      shell: bash

    - run: git config user.email github-actions@github.com
      working-directory: ./example
      shell: bash

    - run: git --work-tree build add --all
      working-directory: ./example
      shell: bash

    - run: git commit -m "Automatic Deploy action run by github-actions"
      working-directory: ./example
      shell: bash

    - run: git push origin HEAD:gh-pages --force
      working-directory: ./example
      shell: bash

